version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "8080:8080"
    networks:
     - dev
  
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: qrtag_1122
      POSTGRES_DB: qrtag
    ports:
      - 5051:5432
    networks:
      - dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
    networks:
      - dev

networks:
  dev: